# Generated by Django 4.2.5 on 2023-09-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parent',
        ),
    ]
