# Generated by Django 4.2.5 on 2023-09-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
