# Generated by Django 4.2.5 on 2023-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name=' description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is_enable'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=55, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name=' updated_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name=' description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='is_enable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=55, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name=' updated_time'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
